import { PageHeader } from "@/components/DashboardWidgets";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

export default function AdminSeating() {
  return (
    <div>
      <PageHeader title="Seating Export" description="Export seating arrangements generated by the seating manager">
        <Button className="gradient-primary text-primary-foreground gap-2"><Download className="w-4 h-4" /> Export All</Button>
      </PageHeader>
      <Card>
        <CardContent className="p-8 text-center text-muted-foreground">
          <p>Seating plans generated by the Seating Manager will appear here for export.</p>
        </CardContent>
      </Card>
    </div>
  );
}
